### 넘파이 텐서 만들기

In [2]:
import numpy as np

In [3]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [6]:
print('rank of t: ', t.ndim) # 차원
print('shape of t: ',t.shape) # 크기

rank of t:  1
shape of t:  (7,)


Numpy

In [9]:
print('t[0]t[1]t[-1] = ', t[0], t[1], t[-1])

t[0]t[1]t[-1] =  0.0 1.0 6.0


In [16]:
print('t[2:5]t[4:-1] = ', t[2:5], t[4:-1])

t[2:5]t[4:-1] =  [2. 3. 4.] [4. 5.]


In [18]:
print('t[:2]t[3:] = ', t[:2], t[3:])

t[:2]t[3:] =  [0. 1.] [3. 4. 5. 6.]


2D Numpy

In [19]:
t = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [21]:
print('rank of t: ', t.ndim)
print('shape of t: ', t.shape)

rank of t:  2
shape of t:  (4, 3)


In [22]:
import torch

In [23]:
t = torch.FloatTensor([0.,1.,2.,3.,4.,5.,6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [25]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [27]:
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [28]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [30]:
print(t.dim())
print(t.size())

2
torch.Size([4, 3])


In [33]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [34]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


브로드캐스팅(Broadcasting)

In [35]:
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [37]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [38]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


행렬 곱셈과 곱셈의 차이(Matrix Multiplication Vs. Multiplication)