In [1]:
from transformers import BartTokenizer, TFBartForConditionalGeneration

# 모델 및 토크나이저 불러오기
model = TFBartForConditionalGeneration.from_pretrained('facebook/bart-base')
tokenizer = BartTokenizer.from_pretrained('facebook/bart-base')

C:\Python\Python39\lib\site-packages\huggingface_hub\file_download.py:133: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\tjoeun\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


All PyTorch model weights were used when initializing TFBartForConditionalGeneration.

All the weights of TFBartForConditionalGeneration were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBartForConditionalGeneration for predictions without further training.


In [2]:
import re

article = """

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence,[9] and consumer electronics. It has been referred to as "the most powerful company in the world"[10] and one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the area of artificial intelligence.[11][12][13] Its parent company Alphabet is considered one of the Big Five American information technology companies, alongside Amazon, Apple, Meta, and Microsoft.

Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a wholly owned subsidiary of Alphabet Inc. Google is Alphabet's largest subsidiary and is a holding company for Alphabet's Internet properties and interests. Sundar Pichai was appointed CEO of Google on October 24, 2015, replacing Larry Page, who became the CEO of Alphabet. On December 3, 2019, Pichai also became the CEO of Alphabet.[14]

The company has since rapidly grown to offer a multitude of products and services beyond Google Search, many of which hold dominant market positions. These products address a wide range of use cases, including email (Gmail), navigation (Waze & Maps), cloud computing (Cloud), web browsing (Chrome), video sharing (YouTube), productivity (Workspace), operating systems (Android), cloud storage (Drive), language translation (Translate), photo storage (Photos), video calling (Meet), smart home (Nest), smartphones (Pixel), wearable technology (Pixel Watch & Fitbit), music streaming (YouTube Music), video on demand (YouTube TV), artificial intelligence (Google Assistant), machine learning APIs (TensorFlow), AI chips (TPU), and more. Discontinued Google products include gaming (Stadia), Glass,[citation needed] Google+, Reader, Play Music, Nexus, Hangouts, and Inbox by Gmail.[15][16]

Google's other ventures outside of Internet services and consumer electronics include quantum computing (Sycamore), self-driving cars (Waymo, formerly the Google Self-Driving Car Project), smart cities (Sidewalk Labs), and transformer models (Google Brain).[17]

Google and YouTube are the two most visited websites worldwide followed by Facebook and Twitter. Google is also the largest search engine, mapping and navigation application, email provider, office suite, video sharing platform, photo and cloud storage provider, mobile operating system, web browser, ML framework, and AI virtual assistant provider in the world as measured by market share. On the list of most valuable brands, Google is ranked second by Forbes[18] and fourth by Interbrand.[19] It has received significant criticism involving issues such as privacy concerns, tax avoidance, censorship, search neutrality, antitrust and abuse of its monopoly position.

"""

print('before:' )
print(article)

before:


Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence,[9] and consumer electronics. It has been referred to as "the most powerful company in the world"[10] and one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the area of artificial intelligence.[11][12][13] Its parent company Alphabet is considered one of the Big Five American information technology companies, alongside Amazon, Apple, Meta, and Microsoft.

Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google

In [5]:
article = re.sub(r"[:.]\[[0-9]+\](.*?)\([0-9]+\)|.?[([][0-9]+[])]|\n|\r", r"", article)
# re regular expression 정규 표현식
# sub (패턴, 대체값, 문장)
print('after: ')
print(article)

after: 
Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software, quantum computing, e-commerce, artificial intelligence and consumer electronics. It has been referred to as "the most powerful company in the world and one of the world's most valuable brands due to its market dominance, data collection, and technological advantages in the area of artificial intelligence Its parent company Alphabet is considered one of the Big Five American information technology companies, alongside Amazon, Apple, Meta, and Microsoft.Google was founded on September 4, 1998, by Larry Page and Sergey Brin while they were PhD students at Stanford University in California. Together they own about 14% of its publicly listed shares and control 56% of the stockholder voting power through super-voting stock. The company went public via an initial public offering (IPO) in 2004. In 2015, Google was reorganized as a whol

In [6]:
inputs = tokenizer([article], max_length=1024, return_tensors='tf', truncation=True)
inputs

{'input_ids': <tf.Tensor: shape=(1, 609), dtype=int32, numpy=
array([[    0, 20441,  2291,    16,    41,   470, 17043,   806,   138,
         5650,    15,  1707,  3819,   806,     6,   804,  4579,     6,
         3613, 11730,     6,  3034,  2257,     6, 17997, 11730,     6,
          364,    12,  8342,     6,  7350,  2316,     8,  2267,  8917,
            4,    85,    34,    57,  4997,     7,    25,    22,   627,
          144,  2247,   138,    11,     5,   232,     8,    65,     9,
            5,   232,    18,   144,  5130,  3595,   528,     7,    63,
          210, 12532,     6,   414,  2783,     6,     8,  9874, 12340,
           11,     5,   443,     9,  7350,  2316,  3139,  4095,   138,
        15023,    16,  1687,    65,     9,     5,  1776,  4934,   470,
          335,   806,   451,     6,  2863,  1645,     6,  1257,     6,
        37622,     6,     8,  3709,     4, 20441,    21,  4790,    15,
          772,   204,     6,  6708,     6,    30,  6045,  7086,     8,
        23509, 

In [13]:
print(inputs['input_ids'].numpy())

[[    0 20441  2291    16    41   470 17043   806   138  5650    15  1707
   3819   806     6   804  4579     6  3613 11730     6  3034  2257     6
  17997 11730     6   364    12  8342     6  7350  2316     8  2267  8917
      4    85    34    57  4997     7    25    22   627   144  2247   138
     11     5   232     8    65     9     5   232    18   144  5130  3595
    528     7    63   210 12532     6   414  2783     6     8  9874 12340
     11     5   443     9  7350  2316  3139  4095   138 15023    16  1687
     65     9     5  1776  4934   470   335   806   451     6  2863  1645
      6  1257     6 37622     6     8  3709     4 20441    21  4790    15
    772   204     6  6708     6    30  6045  7086     8 23509  2265   179
    150    51    58 15221   521    23  8607   589    11   886     4 10853
     51   308    59   501   207     9    63  3271  3147   327     8   797
   4772   207     9     5   388 14074  3434   476   149  2422    12   705
  12653   388     4    20   138   439 

In [14]:
# 문장 요약 생성 결과(vocabulary ID)를 summary_ids에 저장
# num_beams: 의미있는 문장 후보군의 수
summary_ids = model.generate(inputs['input_ids'], num_beams=5, max_length=25)
summary_ids

<tf.Tensor: shape=(1, 25), dtype=int32, numpy=
array([[    2,     0, 20441,  2291,    16,    41,   470, 17043,   806,
          138,  5650,    15,  1707,  3819,   806,     6,   804,  4579,
            6,  3613, 11730,     6,  3034,  2257,     2]])>

 GPT 설명
model.generate(): 이 메소드는 모델을 사용하여 텍스트를 생성하는 함수입니다. 입력으로는 input_ids와 함께 생성에 필요한 다양한 매개변수들을 제공합니다.

inputs['input_ids']: 이 부분은 입력 문장을 나타냅니다. input_ids는 텍스트를 토큰화하여 각 토큰에 대한 고유 식별자(ID)로 변환한 것입니다.

num_beams=5: 생성하는 동안 여러 개의 빔을 사용하여 다양한 후보 문장을 유지하고 선택하는 빔서치 방법입니다. num_beams는 빔의 개수를 나타냅니다. 이 경우 5개의 빔이 사용됩니다.

max_length=25: 생성된 요약 문장의 최대 길이를 제한하는 매개변수입니다. 이 경우 최대 길이가 25로 설정되어 있으므로 생성된 요약은 25개의 토큰을 넘지 않습니다.

마지막으로, summary_ids 변수에는 모델에 의해 생성된 요약 문장의 토큰 ID들이 저장됩니다. 이 요약 문장을 텍스트로 디코딩하여 읽을 수 있습니다. 다음 단계에서 이 summary_ids를 텍스트로 변환하여 실제로 생성된 요약 문장을 얻을 수 있습니다.

In [16]:
# 숫자=>단어
print(''.join([tokenizer.decode(g, skip_special_tokens=True, clean_up_tokenization_spaces=False) for g in summary_ids]))

Google LLC is an American multinational technology company focusing on search engine technology, online advertising, cloud computing, computer software


tokenizer.decode(): 이 함수는 토큰 ID를 텍스트로 디코딩하는 역할을 합니다. 디코딩된 텍스트를 얻기 위해 생성한 요약 문장에 포함된 토큰 ID들을 디코딩합니다.

g는 summary_ids에 있는 각 토큰 ID를 나타내는 변수입니다. 리스트 컴프리헨션 내에서 반복적으로 사용됩니다.

skip_special_tokens=True: 디코딩할 때 특수 토큰(예: [CLS], [SEP], [PAD] 등)을 건너뛰고 실제 텍스트만 반환하도록 설정하는 매개변수입니다.

clean_up_tokenization_spaces=False: 토크나이저가 추가한 공백 문자를 제거하지 않도록 설정하는 매개변수입니다. 이 매개변수가 False로 설정되어 있으면, 토큰화 과정에서 추가된 공백 문자가 그대로 유지됩니다.

summary_ids는 모델이 생성한 요약 문장의 토큰 ID들을 저장하는 변수입니다.