In [29]:
from sklearn.datasets import load_iris
# iris 데이터셋 로딩
X,y = load_iris(return_X_y=True)

In [30]:
print(X[:5])
print(y[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10, stratify=y,shuffle=True)
print(len(X_train))

120


In [32]:
from torch import nn
import torch.nn.functional as F
# 신경망 모형
class Model(nn.Module):
    def __init__(self, input_dim):
        super(Model, self).__init__()
        # input layer, Linear 선형함수(1차함수)
        # input nodes, output nodes 50
        self.layer1 = nn.Linear(input_dim, 50)
        self.layer2 = nn.Linear(50, 20)
        self.layer3 = nn.Linear(20,3)

    def forward(self,x):
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        # 출력층의 활성화 함수 -> softmax
        x = F.softmax(self.layer3(x))
        return x

In [33]:
X_train.shape

(120, 4)

In [34]:
import torch
model = Model(X_train.shape[1]) # 초기화함ㅅ수의 input_dim으로 변수개수가 전달됨
optimizer = torch.optim.Adam(model.parameters(), lr=0.01) # 최적화함수 정의
loss_fn = nn.CrossEntropyLoss() #손실함수 정의
epochs = 100

In [41]:
from torch.autograd import Variable

# 넘파일배열로부터 텐서를 ㅁ나들고
# X_train = Variable(torch.from_numpy(X_train)).float()
# y_train = Variable(torch.from_numpy(y_train)).long() # 정수형 데이터(주로 레이블이나 인덱스 다룰때 사용)

# 2번째 할때부터
X_train = X_train
y_train = y_train
for epoch in range(1, epochs+1):
    print('Epoch', epoch)
    # 예측값
    y_pred = model(X_train)
    # 손실함수에 예측값과 실제값을 입력
    loss = loss_fn(y_pred, y_train)
    print('loss:', loss.item())

    # 경사 초기화
    optimizer.zero_grad()
    loss.backward() #역전파
    optimizer.step() # 가중치 업데이트

    with torch.no_grad():
        y_pred_labels = torch.argmax(y_pred, dim=1) # 가장 높은 확률을 가진 클래스 선택
        accuracy = (y_pred_labels == y_train).float().mean().item()
        print('accuracy: ', accuracy * 100, '%')

Epoch 1
loss: 0.5701541304588318
accuracy:  99.16666746139526 %
Epoch 2
loss: 0.5701271295547485
accuracy:  99.16666746139526 %
Epoch 3
loss: 0.5701005458831787
accuracy:  99.16666746139526 %
Epoch 4
loss: 0.570074200630188
accuracy:  99.16666746139526 %
Epoch 5
loss: 0.5700494050979614
accuracy:  99.16666746139526 %
Epoch 6
loss: 0.5700269341468811
accuracy:  99.16666746139526 %
Epoch 7
loss: 0.5700124502182007
accuracy:  98.33333492279053 %
Epoch 8
loss: 0.5700122714042664
accuracy:  99.16666746139526 %
Epoch 9
loss: 0.5700727105140686
accuracy:  98.33333492279053 %
Epoch 10
loss: 0.5701878666877747
accuracy:  99.16666746139526 %
Epoch 11
loss: 0.5707085728645325
accuracy:  97.50000238418579 %
Epoch 12
loss: 0.5704312920570374
accuracy:  99.16666746139526 %
Epoch 13
loss: 0.570797324180603
accuracy:  97.50000238418579 %
Epoch 14
loss: 0.5701189637184143
accuracy:  99.16666746139526 %
Epoch 15
loss: 0.5699816942214966
accuracy:  98.33333492279053 %
Epoch 16
loss: 0.5699059963226318
ac

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_10152\42384072.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.layer3(x))


In [38]:
X_train

tensor([[6.3000, 2.7000, 4.9000, 1.8000],
        [5.8000, 2.6000, 4.0000, 1.2000],
        [5.0000, 2.0000, 3.5000, 1.0000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [5.6000, 2.8000, 4.9000, 2.0000],
        [6.5000, 3.0000, 5.2000, 2.0000],
        [5.7000, 2.8000, 4.1000, 1.3000],
        [6.0000, 2.7000, 5.1000, 1.6000],
        [5.8000, 2.7000, 5.1000, 1.9000],
        [5.6000, 3.0000, 4.1000, 1.3000],
        [5.1000, 3.5000, 1.4000, 0.3000],
        [5.7000, 3.0000, 4.2000, 1.2000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [6.5000, 3.2000, 5.1000, 2.0000],
        [6.3000, 3.3000, 6.0000, 2.5000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [7.3000, 2.9000, 6.3000, 1.8000],
        [4.8000, 3.0000, 1.4000, 0.3000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [6.6000, 3.0000, 4.4000, 1.4000],
        [6.1000, 2.6000, 5.6000, 1.4000],
        [6.9000, 3.1000, 5.4000, 2.1000],
        [6.1000, 3.0000, 4.6000, 1.4000],
        [5.0000, 3.5000, 1.3000, 0

In [42]:
# Prediction
X_test = Variable(torch.from_numpy(X_test)).float()
pred = model(X_test)
pred[:5]

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_10152\42384072.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.layer3(x))


tensor([[6.2071e-06, 9.9992e-01, 7.1107e-05],
        [9.9979e-01, 2.0849e-04, 4.6261e-12],
        [8.4465e-06, 9.9660e-01, 3.3878e-03],
        [2.9731e-06, 3.5829e-01, 6.4171e-01],
        [2.0741e-03, 9.9793e-01, 2.9516e-07]], grad_fn=<SliceBackward0>)

In [43]:
import numpy as np
np.argmax(pred.data.numpy(), axis=1)
print(np.argmax(pred.data.numpy(), axis=1))

[1 0 1 2 1 2 0 2 2 0 0 1 2 2 1 0 0 1 2 0 2 2 2 0 0 1 1 0 1 1]


In [44]:
from sklearn.metrics import accuracy_score
# 모형의 정확도 측정
accuracy_score(y_test, np.argmax(pred.data.numpy(), axis=1))

1.0

In [45]:
torch.save(model, "c:/work/data/iris/iris-torch.h5")

In [46]:
model2 = torch.load("c:/work/data/iris/iris-torch.h5")
np.argmax(model2(X_test[0]).data.numpy())

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_10152\42384072.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.layer3(x))


1

In [47]:
y_test[0]

1

In [48]:
from torchinfo import summary
summary(model)
# input_size=(batch size, input nodes)

summary(model, input_size=(32, 4))

C:\Users\tjoeun\AppData\Local\Temp\ipykernel_10152\42384072.py:17: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  x = F.softmax(self.layer3(x))


Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [32, 3]                   --
├─Linear: 1-1                            [32, 50]                  250
├─Linear: 1-2                            [32, 20]                  1,020
├─Linear: 1-3                            [32, 3]                   63
Total params: 1,333
Trainable params: 1,333
Non-trainable params: 0
Total mult-adds (M): 0.04
Input size (MB): 0.00
Forward/backward pass size (MB): 0.02
Params size (MB): 0.01
Estimated Total Size (MB): 0.02

In [49]:
summary(model)

Layer (type:depth-idx)                   Param #
Model                                    --
├─Linear: 1-1                            250
├─Linear: 1-2                            1,020
├─Linear: 1-3                            63
Total params: 1,333
Trainable params: 1,333
Non-trainable params: 0