In [1]:
from sklearn.datasets import load_wine

In [2]:
wine = load_wine()

In [3]:
wine

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [4]:
import pandas as pd
pd.DataFrame(wine.data, columns=wine.feature_names)

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0      14.23        1.71  2.43               15.6      127.0           2.80   
1      13.20        1.78  2.14               11.2      100.0           2.65   
2      13.16        2.36  2.67               18.6      101.0           2.80   
3      14.37        1.95  2.50               16.8      113.0           3.85   
4      13.24        2.59  2.87               21.0      118.0           2.80   
..       ...         ...   ...                ...        ...            ...   
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0          3.06                  0.28             2.29             5.64  1.04   
1          2.76                  0.26             1.28             4.38  1.05   
2          3.24                  0.30             2.81             5.68  1.03   
3          3.49                  0.24             2.18             7.80  0.86   
4          2.69                  0.39             1.82             4.32  1.04   
..          ...                   ...              ...              ...   ...   
173        0.61                  0.52             1.06             7.70  0.64   
174        0.75                  0.43             1.41             7.30  0.70   
175        0.69                  0.43             1.35            10.20  0.59   
176        0.68                  0.53             1.46             9.30  0.60   
177        0.76                  0.56             1.35             9.20  0.61   

     od280/od315_of_diluted_wines  proline  
0                            3.92   1065.0  
1                            3.40   1050.0  
2                            3.17   1185.0  
3                            3.45   1480.0  
4                            2.93    735.0  
..                            ...      ...  
173                          1.74    740.0  
174                          1.56    750.0  
175                          1.56    835.0  
176                          1.62    840.0  
177                          1.60    560.0  

[178 rows x 13 columns]

In [5]:
wine.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [7]:
# 독립변수
X = wine.data
# 종속변수
y = wine.target

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
print(len(X_train))
print(len(y_train))

142
142


In [16]:
import torch
# 학습용 데이터를 텐서로 변환
X_train = torch.from_numpy(X_train).float()
y_train = torch.from_numpy(y_train).long()

# 검증용 데이터를 텐서로 변환
X_test = torch.from_numpy(X_test).float()
y_test = torch.from_numpy(y_test).long()

In [17]:
# 텐서를 gpu로 옮기고
X_train = X_train.cuda()
y_train= y_train.cuda()
X_test = X_test.cuda()
y_test= y_test.cuda()

In [18]:
X_train

tensor([[1.1840e+01, 2.8900e+00, 2.2300e+00,  ..., 9.6000e-01, 2.5200e+00,
         5.0000e+02],
        [1.3050e+01, 1.7300e+00, 2.0400e+00,  ..., 1.1200e+00, 2.9100e+00,
         1.1500e+03],
        [1.3050e+01, 5.8000e+00, 2.1300e+00,  ..., 7.3000e-01, 3.1000e+00,
         3.8000e+02],
        ...,
        [1.2080e+01, 1.3900e+00, 2.5000e+00,  ..., 9.3000e-01, 3.1900e+00,
         3.8500e+02],
        [1.3710e+01, 5.6500e+00, 2.4500e+00,  ..., 6.4000e-01, 1.7400e+00,
         7.4000e+02],
        [1.4750e+01, 1.7300e+00, 2.3900e+00,  ..., 1.2500e+00, 2.7300e+00,
         1.1500e+03]], device='cuda:0')

In [19]:
from torch.utils.data import DataLoader, TensorDataset
# 독립변수와 종속변수의 텐서를 합침
train = TensorDataset(X_train, y_train)
print(train[0])
# 미니배치로 분할
train_loader = DataLoader(train, batch_size=16, shuffle=True)

(tensor([1.1840e+01, 2.8900e+00, 2.2300e+00, 1.8000e+01, 1.1200e+02, 1.7200e+00,
        1.3200e+00, 4.3000e-01, 9.5000e-01, 2.6500e+00, 9.6000e-01, 2.5200e+00,
        5.0000e+02], device='cuda:0'), tensor(1, device='cuda:0'))


In [21]:
X_train.shape # input=13

torch.Size([142, 13])

In [32]:
import torch.nn as nn
import torch.nn.functional as F
# 신경망 구성
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(13, 96) # input13, output 96
        self.fc2 = nn.Linear(96, 72)
        self.fc3 = nn.Linear(72, 64)
        self.fc4 = nn.Linear(64, 32)
        self.fc5 = nn.Linear(32, 16)
        self.fc6 = nn.Linear(16, 3)
    
    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = F.relu(self.fc3(x))
        x = F.relu(self.fc4(x))
        x = F.relu(self.fc5(x))
        x = self.fc6(x)
        # softmax 함수의 결과값에 log 적용
        # dim=0 행방향, 1 열방향
        # dim=0, row에서 최대값을 구하는 방식
        return F.log_softmax(x,dim=0)

# 인스턴스 생성
model = Net().cuda()

In [33]:
model

Net(
  (fc1): Linear(in_features=13, out_features=96, bias=True)
  (fc2): Linear(in_features=96, out_features=72, bias=True)
  (fc3): Linear(in_features=72, out_features=64, bias=True)
  (fc4): Linear(in_features=64, out_features=32, bias=True)
  (fc5): Linear(in_features=32, out_features=16, bias=True)
  (fc6): Linear(in_features=16, out_features=3, bias=True)
)

In [34]:
import torch.optim as optim
from torch.autograd import Variable

# 손실함수 객체
criterion = nn.CrossEntropyLoss()

# 최적화함수
optimizer = optim.SGD(model.parameters(), lr=0.001)

In [35]:
# 학습시작

for epoch in range(500):
    total_loss = 0
    for train_x, train_y in train_loader:
        
        # 계산 그래프 구성
        train_x, train_y = Variable(train_x), Variable(train_y)
        
        #텐서를 gpu로 이동시킴
        train_x=train_x.cuda()
        train_y=train_y.cuda()        

        # 경사 초기화
        optimizer.zero_grad()

        # 순전파 계산
        output = model(train_x)

        # 오차계산
        loss = criterion(output, train_y)

        # 역전파 계산
        loss.backward()

        # 가중치 업데이트
        optimizer.step()

        # 누적 오차 계산
        total_loss += loss.data

    # 50회 반복마다 누적오차 출력
    if (epoch+1) % 50 == 0:
        print(epoch+1, total_loss)

50 tensor(5.4996, device='cuda:0')
100 tensor(5.2968, device='cuda:0')
150 tensor(5.2356, device='cuda:0')
200 tensor(5.5133, device='cuda:0')
250 tensor(5.1146, device='cuda:0')
300 tensor(5.1406, device='cuda:0')
350 tensor(5.9508, device='cuda:0')
400 tensor(5.5084, device='cuda:0')
450 tensor(5.1416, device='cuda:0')
500 tensor(4.8328, device='cuda:0')


In [38]:
# 계산 그래프 구성
X_test, y_test = Variable(X_test), Variable(y_test)

# 출력값 계산
result = torch.max(model(X_test).data,1)[1]

# 모형의 정확도 측정
# gpu에 저장된 텐서를 cpu로 이동시킴
y_test = y_test.cpu()
result = result.cpu()
accuracy = sum(y_test.data.numpy() == result.numpy()) / len(y_test.data.numpy())

# 모형의 정확도 출력
accuracy

0.6111111111111112