In [1]:
import torch
# gpu 사용 가능 여부
print(torch.cuda.is_available())
# True


True


In [2]:
# gpu 장치의 인덱스
print(torch.cuda.current_device())

0


In [3]:
# 사용 가능한 gpu 장치수
print(torch.cuda.device_count())

1


In [4]:
# gpu의 이름
print(torch.cuda.get_device_name(0))

NVIDIA GeForce GTX 1050


In [5]:
import torch

In [10]:
# default CUDA device
cuda = torch.device('cuda')

cuda


In [14]:
# 텐서 자료를 gpu에 저장
a = torch.tensor([1,2], device=cuda)
b = torch.tensor([1,2]).cuda()
c = torch.tensor([1,2]).to(device=cuda)
print(a)
print(b)
print(c)

tensor([1, 2], device='cuda:0')
tensor([1, 2], device='cuda:0')
tensor([1, 2], device='cuda:0')


In [15]:
# 사용하지 않는 텐서 정리
torch.cuda.empty_cache()